---
title: "Grant Neilson's Resume"
author: Grant Neilson
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'dd_resume.css', 'resume']
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

source(here::here("R/cv_printing_functions.r"))

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = stringr::str_c(here::here("data"), "/"),
  pdf_mode = params$pdf_mode
)

CV[["entries_data"]] <- CV[["entries_data"]] |>
  dplyr::filter(as.logical(in_cv))

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================


```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```



```{r}
if(params$pdf_mode){
  cat("View this resume online with links at _nickstrayer.me/datadrivencv/resume_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/nstrayer/cv/raw/master/strayer_resume.pdf)")
}
```


For a longer form version, see my [CV](nickstrayer.me/cv/).

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV |> print_contact_info()
```



Languages {#languages}
--------------------------------------------------------------------------------

```{r}
CV |> print_skills("language")
```

Technologies {#technologies}
--------------------------------------------------------------------------------

```{r}
CV |> print_skills("technology")
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available at [https://github.com/grantneilson/cv](https://github.com/grantneilson/cv).

Last updated on `r Sys.Date()`.



Main
================================================================================

Grant Neilson {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV <- print_text_block(CV, "intro") 
```


Industry Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'industry_positions')
```


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'education')
```


Selected Publications {data-icon=book}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'academic_articles')
```


```{r}
print_links(CV)
```

