name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-cv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up R library path
        run: echo "R_LIBS_USER=${{ runner.temp }}/Rlib" >> $GITHUB_ENV

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/Rlib
          key: r-${{ runner.os }}-${{ hashFiles('**/DESCRIPTION') }}-${{ steps.date.outputs.date }}
          restore-keys: |
            r-${{ runner.os }}-
      - name: Get date for cache key
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%H')" >> $GITHUB_OUTPUT

      - name: Install curl
        run: sudo apt-get install libcurl4-openssl-dev

      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install dependencies
        run: |
          install.packages(
            c("rmarkdown", "pagedown", "googlesheets4", "purrr", "dplyr", "readr", "tidyr", "lubridate", "here", "stringr"),
            lib = Sys.getenv("R_LIBS_USER"),
            repos = "https://cloud.r-project.org"
          )
        shell: Rscript {0}
        env:
          R_LIBS_USER: ${{ runner.temp }}/Rlib

      - name: Create docs
        run: |
          mkdir -p docs

      - name: Render cv
        run: |
          source("render_cv.r")
        shell: Rscript {0}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
