name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-cv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create docs directory
        run: mkdir -p docs

      - name: Build docs in Docker (rocker/r-ver)
        uses: addnab/docker-run-action@v3
        with:
          image: rocker/shiny:4.4 # or whichever R version you want
          options: -v ${{ github.workspace }}:/workspace
          run: |
            Rscript -e 'install.packages(c("rmarkdown", "pagedown", "purrr", "dplyr", "readr", "tidyr", "lubridate", "here", "stringr"), repos="https://cloud.r-project.org")'
            cd /workspace
            Rscript render_cv.r

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          CLEAN: true
