name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-cv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create docs directory
        run: mkdir -p docs

      - name: Render CV in Docker
        uses: addnab/docker-run-action@v3
        with:
          image: rocker/shiny:latest
          options: -v ${{ github.workspace }}:/workspace
          run: |
            Rscript -e 'install.packages(c("lubridate", "here"), repos="https://cloud.r-project.org")'
            cd /workspace
            Rscript render_cv.r

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          CLEAN: true
